### ISSUE TITLE
got an error at options.namespaces?.iTunes 

### ISSUE THREAD

**Issue by kouohhashi** [maxnowack/node-podcast#53]
Hi, when I try to load podcast library, I got an error like this.

```
import { Podcast } from 'podcast';
```

Error message was 
```
./node_modules/podcast/dist/cjs/index.js:63
        if (options.namespaces?.iTunes) {
                               ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module._compile (./node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.newLoader [as .js] (./node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (./server/routes/editor_api.js:81:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! editor_web_api@1.0.0 server: `BABEL_DISABLE_CACHE=1 babel-node server "prod3"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the editor_web_api@1.0.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

my node version: v12.22.7
my npm version: 6.14.15

Is my node too old?

thanks in advance

**Comment by kouohhashi** [comment]
My bad.
When I upgraded Node version to v14.18.2 and it worked.
